--- #YAML:1.0
name:               IMDB-Film
version:            0.46
abstract:           OO Perl interface to the movies database IMDB.
author:
    - Michael Stepanov <stepanov.michael@gmail.com>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Cache::FileCache:  0
    Carp:              0
    Digest::SHA1:      0
    Error:             0
    HTML::Entities:    0
    HTML::TokeParser:  2.28
    LWP::Simple:       1.41
    Pod::Checker:      0
    Text::Unidecode:   0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
