---
abstract: 'OO Perl interface to the movies database IMDB.'
author:
  - 'Michael Stepanov <stepanov.michael@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.120630'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: IMDB-Film
no_index:
  directory:
    - t
    - inc
requires:
  Cache::FileCache: 0
  Carp: 0
  Digest::SHA1: 0
  Error: 0
  HTML::Entities: 0
  HTML::TokeParser: 2.28
  LWP::Simple: 1.41
  Pod::Checker: 0
  Text::Unidecode: 0
version: 0.53
