# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         IMDB-Film
version:      0.02
version_from: lib/IMDB/Film.pm
installdirs:  site
requires:
    Cache::Cache:                  1.02
    Carp:                          0
    HTML::TokeParser:              2.28
    LWP::UserAgent:                2.024

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
